// Generated from tools/assets/vectors.mjs. Keep the visible label beside each icon.
export const iconLabels = {
  "home": "Домой",
  "search": "Поиск",
  "overview": "Обзор",
  "legend": "Легенда",
  "back": "Назад",
  "forward": "Вперёд",
  "up": "На уровень выше",
  "history": "Недавнее",
  "bookmark": "Закладки",
  "zoom-in": "Приблизить",
  "zoom-out": "Отдалить",
  "fit": "Показать всё",
  "person": "Персона",
  "person-add": "Добавить человека",
  "person-edit": "Изменить данные",
  "parents": "Родители",
  "children": "Дети",
  "partners": "Партнёры",
  "siblings": "Братья и сёстры",
  "ancestor": "Предок",
  "descendants": "Потомки",
  "living": "Живущий человек",
  "deceased": "Умерший человек",
  "birth": "Рождение",
  "marriage": "Брак",
  "relationship": "Родственная связь",
  "pin": "Закрепить",
  "family-tree": "Семейное древо",
  "source": "Источник",
  "source-add": "Добавить источник",
  "archive": "Архив",
  "book": "Книга",
  "document": "Документ",
  "citation": "Цитата",
  "verified": "Подтверждено",
  "uncertain": "Предположительно",
  "conflict": "Разночтение",
  "research": "Исследование",
  "note": "Заметка",
  "folder": "Папка",
  "link": "Связать",
  "transcript": "Расшифровка",
  "image": "Фотография",
  "image-add": "Добавить фотографию",
  "scan": "Сканировать",
  "crop": "Обрезать",
  "rotate": "Повернуть",
  "download": "Скачать",
  "upload": "Загрузить",
  "print": "Печать",
  "original": "Оригинал",
  "attachment": "Вложение",
  "sync": "Синхронизация",
  "offline": "Нет связи",
  "cloud": "Облако",
  "local": "На устройстве",
  "contribution": "Предложить изменение",
  "review": "Проверить изменения",
  "accept": "Принять",
  "reject": "Отклонить",
  "merge": "Объединить",
  "compare": "Сравнить",
  "backup": "Резервная копия",
  "restore": "Восстановить",
  "atlas": "Атлас",
  "fan": "Веер",
  "hourglass": "Песочные часы",
  "strata": "Стратиграфия",
  "flows": "Потоки",
  "kinship": "Родство",
  "genogram": "Генограмма",
  "geography": "География",
  "settings": "Настройки",
  "help": "Помощь",
  "accessibility": "Доступность",
  "theme": "Свет и лампа",
  "language": "Язык",
  "lock": "Закрытый доступ",
  "export": "Экспорт",
  "import": "Импорт"
} as const;
export type IconName = keyof typeof iconLabels;
