//! Bringing a colour into sRGB without destroying it.
//!
//! An OKLCH colour can name a light that no sRGB display can emit. Something has to give, and
//! the naive answer — clip each channel into range — is the wrong one: clipping a saturated
//! colour shifts its hue, so a ramp generated by clipping drifts sideways as it gets darker,
//! and the eleven stops no longer read as one family.
//!
//! This implements the CSS Color 4 gamut-mapping algorithm: hold lightness and hue, binary
//! search downward on chroma, and stop as soon as a clipped version is within a just-noticeable
//! difference of the unclipped one. Hue is preserved by construction.

use crate::oklab::{Oklch, delta_eok};
use crate::srgb::Srgb;

/// A just-noticeable difference in OKLab, as CSS Color 4 defines it for this purpose.
const JND: f64 = 0.02;

/// Where the binary search stops. 0.0001 of chroma is far below display resolution.
const CHROMA_EPSILON: f64 = 1e-4;

/// Maximum iterations. The search halves the interval each time, so this is ample; the bound
/// exists so a pathological input cannot hang a build or a frame.
const MAX_STEPS: usize = 32;

/// Maps an OKLCH colour into sRGB, preserving lightness and hue.
///
/// Returns the colour unchanged when it is already displayable.
#[must_use]
pub fn to_srgb_mapped(colour: Oklch) -> Srgb {
    let direct = colour.to_srgb_unmapped();
    if direct.in_gamut() {
        return clip(direct);
    }

    // Beyond the ends of the lightness axis there is nothing to search for: every chroma is
    // out of gamut and the answer is simply black or white.
    if colour.l >= 1.0 {
        return Srgb::new(1.0, 1.0, 1.0);
    }
    if colour.l <= 0.0 {
        return Srgb::new(0.0, 0.0, 0.0);
    }

    let mut low = 0.0;
    let mut high = colour.c;
    let mut best = clip(colour.with_chroma(0.0).to_srgb_unmapped());

    for _ in 0..MAX_STEPS {
        if high - low < CHROMA_EPSILON {
            break;
        }
        let mid = f64::midpoint(low, high);
        let candidate = colour.with_chroma(mid);
        let unclipped = candidate.to_srgb_unmapped();

        if unclipped.in_gamut() {
            best = clip(unclipped);
            low = mid;
            continue;
        }

        // Out of gamut — but if clipping it lands within a just-noticeable difference, that is
        // a better answer than reducing chroma further, and CSS Color 4 says to take it.
        let clipped = clip(unclipped);
        let difference = delta_eok(Oklch::from_srgb(clipped).to_oklab(), candidate.to_oklab());
        if difference < JND {
            best = clipped;
            break;
        }
        high = mid;
    }

    best
}

/// Whether an OKLCH colour can be displayed in sRGB as it stands.
#[must_use]
pub fn is_displayable(colour: Oklch) -> bool {
    colour.to_srgb_unmapped().in_gamut()
}

/// Returns the largest chroma that is displayable at this colour's lightness and hue.
///
/// Useful when generating a ramp: it says how much saturation a given lightness can actually
/// carry, so stops near black and white stop asking for chroma that does not exist.
#[must_use]
pub fn max_chroma(lightness: f64, hue: f64) -> f64 {
    if !(0.0..=1.0).contains(&lightness) {
        return 0.0;
    }
    // At the poles there is no chroma to find. Without this the binary search creeps upward:
    // near black, an out-of-gamut colour's components are so small that they fall inside the
    // round-trip tolerance `in_gamut` allows, and the search mistakes them for displayable.
    if lightness <= f64::EPSILON || lightness >= 1.0 - f64::EPSILON {
        return 0.0;
    }
    let mut low = 0.0;
    // 0.4 is comfortably beyond anything sRGB can reach at any lightness.
    let mut high = 0.4;
    for _ in 0..MAX_STEPS {
        if high - low < CHROMA_EPSILON {
            break;
        }
        let mid = f64::midpoint(low, high);
        if Oklch::new(lightness, mid, hue)
            .to_srgb_unmapped()
            .in_gamut()
        {
            low = mid;
        } else {
            high = mid;
        }
    }
    low
}

fn clip(c: Srgb) -> Srgb {
    Srgb::new(
        c.r.clamp(0.0, 1.0),
        c.g.clamp(0.0, 1.0),
        c.b.clamp(0.0, 1.0),
    )
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::panic)]

    use super::{is_displayable, max_chroma, to_srgb_mapped};
    use crate::oklab::Oklch;
    use crate::srgb::Srgb;

    #[test]
    fn in_gamut_colours_pass_through_unchanged() {
        for hex in ["#B4552C", "#6B8163", "#FBF7EE", "#1E232B"] {
            let original = Srgb::from_hex(hex).unwrap();
            let mapped = to_srgb_mapped(Oklch::from_srgb(original));
            assert_eq!(mapped.to_hex(), original.to_hex(), "{hex} was altered");
        }
    }

    #[test]
    fn out_of_gamut_colours_come_back_displayable() {
        for (l, c, h) in [
            (0.7, 0.35, 150.0),
            (0.5, 0.30, 270.0),
            (0.85, 0.25, 30.0),
            (0.2, 0.28, 320.0),
        ] {
            let mapped = to_srgb_mapped(Oklch::new(l, c, h));
            assert!(mapped.in_gamut(), "({l}, {c}, {h}) mapped out of gamut");
        }
    }

    #[test]
    fn mapping_preserves_hue_for_reachable_colours() {
        // The property clipping destroys, and the reason this algorithm exists — asserted at
        // chroma the gamut can nearly deliver, which is where hue fidelity is contractual.
        for hue in [0.0, 42.0, 142.0, 186.0, 266.0, 330.0] {
            let reachable = max_chroma(0.6, hue);
            let wanted = Oklch::new(0.6, reachable * 1.05, hue);
            let got = Oklch::from_srgb(to_srgb_mapped(wanted));
            let drift = (got.h - hue).abs().min(360.0 - (got.h - hue).abs());
            assert!(drift < 2.0, "hue {hue} drifted to {} ({drift}°)", got.h);
        }
    }

    #[test]
    fn far_out_of_gamut_colours_trade_hue_for_the_jnd_shortcut() {
        // Documenting a real property of CSS Color 4 rather than pretending it away: when a
        // colour is far outside sRGB, the algorithm accepts a clipped result that is within a
        // just-noticeable difference, and clipping moves hue. Up to about 13° at extreme
        // chroma.
        //
        // We keep the standard's behaviour deliberately. The browser applies the same
        // algorithm to an `oklch()` value in a stylesheet, and a mapper that disagreed with it
        // would make our generated hex fallbacks differ from the live colour beside them.
        //
        // Ramps avoid the whole situation by clamping chroma to what the lightness can carry
        // before mapping — see `ramp::Ramp::from_identity`.
        let wanted = Oklch::new(0.2, 0.30, 42.0);
        let got = Oklch::from_srgb(to_srgb_mapped(wanted));
        assert!(to_srgb_mapped(wanted).in_gamut());
        let drift = (got.h - 42.0).abs().min(360.0 - (got.h - 42.0).abs());
        assert!(
            drift < 20.0,
            "drift of {drift}° is beyond even the shortcut's reach"
        );
    }

    #[test]
    fn mapping_roughly_preserves_lightness() {
        for lightness in [0.2, 0.4, 0.6, 0.8] {
            let got = Oklch::from_srgb(to_srgb_mapped(Oklch::new(lightness, 0.33, 210.0)));
            assert!(
                (got.l - lightness).abs() < 0.06,
                "L {lightness} became {}",
                got.l
            );
        }
    }

    #[test]
    fn extremes_resolve_to_black_and_white() {
        assert_eq!(
            to_srgb_mapped(Oklch::new(1.0, 0.3, 90.0)).to_hex(),
            "#FFFFFF"
        );
        assert_eq!(
            to_srgb_mapped(Oklch::new(0.0, 0.3, 90.0)).to_hex(),
            "#000000"
        );
        assert_eq!(
            to_srgb_mapped(Oklch::new(1.5, 0.3, 90.0)).to_hex(),
            "#FFFFFF"
        );
    }

    #[test]
    fn max_chroma_is_a_real_boundary() {
        for (l, h) in [(0.5, 30.0), (0.7, 150.0), (0.3, 260.0), (0.9, 90.0)] {
            let limit = max_chroma(l, h);
            assert!(limit > 0.0, "no chroma available at L={l} H={h}");
            assert!(
                is_displayable(Oklch::new(l, limit, h)),
                "limit not displayable"
            );
            assert!(
                !is_displayable(Oklch::new(l, limit + 0.01, h)),
                "L={l} H={h}: chroma beyond the limit was still displayable"
            );
        }
    }

    #[test]
    fn max_chroma_vanishes_at_the_ends_of_the_lightness_axis() {
        assert!(max_chroma(0.0, 120.0) < 1e-3);
        assert!(max_chroma(1.0, 120.0) < 1e-3);
        // Out of range entirely: the answer is exactly zero, not approximately.
        assert!(max_chroma(-0.1, 120.0).abs() < f64::EPSILON);
        assert!(max_chroma(1.1, 120.0).abs() < f64::EPSILON);
    }

    #[test]
    fn clamping_chroma_first_is_what_keeps_a_ramp_on_one_hue() {
        // Eleven stops must read as one family. Asking for a fixed chroma at every lightness
        // does not achieve that — dark stops go far out of gamut and the JND shortcut swings
        // their hue. Clamping to the chroma each lightness can actually carry does achieve it,
        // which is why `Ramp::from_identity` does exactly that.
        let hue = 42.0;
        for i in 0..=10 {
            let l = 0.08 + f64::from(i) * 0.09;
            let chroma = 0.16_f64.min(max_chroma(l, hue));
            if chroma < 0.02 {
                continue; // too near grey for a hue to mean anything
            }
            let got = Oklch::from_srgb(to_srgb_mapped(Oklch::new(l, chroma, hue))).h;
            let drift = (got - hue).abs().min(360.0 - (got - hue).abs());
            assert!(
                drift < 2.0,
                "stop at L={l:.2} drifted {drift:.1}° to {got:.1}"
            );
        }
    }
}
