// Generated by tools/assets/build.mjs from tools/assets/vectors.mjs. Do not edit.
//
// The label is part of the data because an icon without a visible label fails the primary
// persona, and a caller who has to remember to add one will eventually forget.

export interface IconShape {
  readonly kind: 'path' | 'circle';
  readonly d?: string;
  readonly cx?: number;
  readonly cy?: number;
  readonly r?: number;
}

export interface IconDefinition {
  /** The Russian label that must be shown beside the glyph. */
  readonly label: string;
  /** Which of the seven categories it belongs to. */
  readonly category: string;
  /** The geometry, on a 24 unit grid. */
  readonly shapes: readonly IconShape[];
}

export const icons = {
  "home": {
    "label": "Домой",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 11 12 3 21 11 M5 10v11h5v-7h4v7h5V10"
      }
    ]
  },
  "search": {
    "label": "Поиск",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M16 16 21 21"
      },
      {
        "kind": "circle",
        "cx": 10,
        "cy": 10,
        "r": 7
      }
    ]
  },
  "overview": {
    "label": "Обзор",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3h18v18H3z M6 7h5v4H6z M9 10h9v8H9z"
      }
    ]
  },
  "legend": {
    "label": "Легенда",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M10 5h11 M10 12h11 M10 19h11 M3 3h4v4H3z M3 17h4v4H3z"
      },
      {
        "kind": "circle",
        "cx": 5,
        "cy": 12,
        "r": 2
      }
    ]
  },
  "back": {
    "label": "Назад",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M20 12H4 M10 6l-6 6 6 6"
      }
    ]
  },
  "forward": {
    "label": "Вперёд",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M4 12h16 M14 6l6 6-6 6"
      }
    ]
  },
  "up": {
    "label": "На уровень выше",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 21V3 M6 9l6-6 6 6"
      }
    ]
  },
  "history": {
    "label": "Недавнее",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 4v6h6 M3 10a9 9 0 1 1 1 8 M12 7v5l4 2"
      }
    ]
  },
  "bookmark": {
    "label": "Закладки",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M6 3h12v18l-6-4-6 4z"
      }
    ]
  },
  "zoom-in": {
    "label": "Приблизить",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M16 16l5 5 M7 10h6 M10 7v6"
      },
      {
        "kind": "circle",
        "cx": 10,
        "cy": 10,
        "r": 7
      }
    ]
  },
  "zoom-out": {
    "label": "Отдалить",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M16 16l5 5 M7 10h6"
      },
      {
        "kind": "circle",
        "cx": 10,
        "cy": 10,
        "r": 7
      }
    ]
  },
  "fit": {
    "label": "Показать всё",
    "category": "navigation",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 8V3h5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M8 8h8v8H8z"
      }
    ]
  },
  "person": {
    "label": "Персона",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 21v-3a7 7 0 0 1 14 0v3"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 6,
        "r": 3
      }
    ]
  },
  "person-add": {
    "label": "Добавить человека",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 21v-3a6 6 0 0 1 10-4 M18 12v8 M14 16h8"
      },
      {
        "kind": "circle",
        "cx": 9,
        "cy": 6,
        "r": 3
      }
    ]
  },
  "person-edit": {
    "label": "Изменить данные",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 21v-3a6 6 0 0 1 7-6 M12 19l-1 3 3-1 8-8-2-2z"
      },
      {
        "kind": "circle",
        "cx": 9,
        "cy": 6,
        "r": 3
      }
    ]
  },
  "parents": {
    "label": "Родители",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 9v4h14V9 M12 13v5"
      },
      {
        "kind": "circle",
        "cx": 5,
        "cy": 5,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 19,
        "cy": 5,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 21,
        "r": 2
      }
    ]
  },
  "children": {
    "label": "Дети",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 7v5 M5 18v-6h14v6"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 4,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 5,
        "cy": 21,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 19,
        "cy": 21,
        "r": 2
      }
    ]
  },
  "partners": {
    "label": "Партнёры",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M8 9h8 M4 14v7 M20 14v7 M2 21h6 M16 21h6"
      },
      {
        "kind": "circle",
        "cx": 4,
        "cy": 9,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 20,
        "cy": 9,
        "r": 3
      }
    ]
  },
  "siblings": {
    "label": "Братья и сёстры",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v6 M5 14V9h14v5 M2 22v-2a3 3 0 0 1 6 0v2 M16 22v-2a3 3 0 0 1 6 0v2"
      },
      {
        "kind": "circle",
        "cx": 5,
        "cy": 15,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 19,
        "cy": 15,
        "r": 2
      }
    ]
  },
  "ancestor": {
    "label": "Предок",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3 20 11 12 19 4 11z M12 7l4 4-4 4-4-4z M12 19v3"
      }
    ]
  },
  "descendants": {
    "label": "Потомки",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 5v7 M5 18v-6h14v6"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 4,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 5,
        "cy": 20,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 19,
        "cy": 20,
        "r": 2
      }
    ]
  },
  "living": {
    "label": "Живущий человек",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v9h9 M3 12a9 9 0 1 0 9-9"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 12,
        "r": 9
      }
    ]
  },
  "deceased": {
    "label": "Умерший человек",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v18 M6 8h12"
      }
    ]
  },
  "birth": {
    "label": "Рождение",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v18 M3 12h18 M5.5 5.5l13 13 M5.5 18.5l13-13"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 12,
        "r": 3
      }
    ]
  },
  "marriage": {
    "label": "Брак",
    "category": "family",
    "shapes": [
      {
        "kind": "circle",
        "cx": 8,
        "cy": 12,
        "r": 6
      },
      {
        "kind": "circle",
        "cx": 16,
        "cy": 12,
        "r": 6
      }
    ]
  },
  "relationship": {
    "label": "Родственная связь",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M7 6h5v12h5"
      },
      {
        "kind": "circle",
        "cx": 4,
        "cy": 6,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 20,
        "cy": 18,
        "r": 3
      }
    ]
  },
  "pin": {
    "label": "Закрепить",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M8 3h8 M9 3v7l-3 4h12l-3-4V3 M12 14v8"
      }
    ]
  },
  "family-tree": {
    "label": "Семейное древо",
    "category": "family",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 7v5 M5 17v-5h14v5 M9 3h6v4H9z M2 17h6v4H2z M16 17h6v4h-6z"
      }
    ]
  },
  "source": {
    "label": "Источник",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 3h10l4 4v14H5z M15 3v5h4 M8 12h8 M8 16h6"
      }
    ]
  },
  "source-add": {
    "label": "Добавить источник",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 21V3h10l4 4v5 M15 3v5h4 M8 12h4 M16 15v7 M12.5 18.5h7"
      }
    ]
  },
  "archive": {
    "label": "Архив",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 4h18v5H3z M5 9v12h14V9 M9 13h6"
      }
    ]
  },
  "book": {
    "label": "Книга",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 5v16 M12 5C8 2 5 3 2 4v15c3-1 6-1 10 2 4-3 7-3 10-2V4c-3-1-6-2-10 1"
      }
    ]
  },
  "document": {
    "label": "Документ",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 3h10l4 4v14H5z M15 3v5h4 M8 11h8 M8 15h8 M8 18h5"
      }
    ]
  },
  "citation": {
    "label": "Цитата",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M9 5C5 5 3 9 3 13h6v7H3v-7 M21 5c-4 0-6 4-6 8h6v7h-6v-7"
      }
    ]
  },
  "verified": {
    "label": "Подтверждено",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 12l4 4 10-11"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 12,
        "r": 9
      }
    ]
  },
  "uncertain": {
    "label": "Предположительно",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4 M12 18v.1"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 12,
        "r": 10
      }
    ]
  },
  "conflict": {
    "label": "Разночтение",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 2 22 12 12 22 2 12z M12 7v6 M12 17v.1"
      }
    ]
  },
  "research": {
    "label": "Исследование",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 21 5 14 16 3l5 5-11 11z M5 14l5 5 M13 6l5 5 M3 21l5-2"
      }
    ]
  },
  "note": {
    "label": "Заметка",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M4 3h16v12l-6 6H4z M14 21v-6h6 M8 7h8 M8 11h6"
      }
    ]
  },
  "folder": {
    "label": "Папка",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 6h7l2 3h9v12H3z M3 6V3h7l2 3h9v3"
      }
    ]
  },
  "link": {
    "label": "Связать",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M10 14l4-4 M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0 M16 8l1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"
      }
    ]
  },
  "transcript": {
    "label": "Расшифровка",
    "category": "sources",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3h8v18H3z M5 7h4 M5 11h4 M15 5h6 M15 9h6 M15 13h6 M15 17h4"
      }
    ]
  },
  "image": {
    "label": "Фотография",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5"
      },
      {
        "kind": "circle",
        "cx": 16,
        "cy": 7,
        "r": 2
      }
    ]
  },
  "image-add": {
    "label": "Добавить фотографию",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M11 21H3V3h18v8 M3 17l6-6 4 4 M18 14v8 M14 18h8"
      },
      {
        "kind": "circle",
        "cx": 16,
        "cy": 7,
        "r": 2
      }
    ]
  },
  "scan": {
    "label": "Сканировать",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 8V3h5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5 M3 12h18 M7 7h10v10H7z"
      }
    ]
  },
  "crop": {
    "label": "Обрезать",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M7 2v15h15 M2 7h15v15 M4 20l16-16"
      }
    ]
  },
  "rotate": {
    "label": "Повернуть",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M18 3v5h-5 M18 8a8 8 0 1 0 2 8 M8 10h6v6H8z"
      }
    ]
  },
  "download": {
    "label": "Скачать",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v12 M7 10l5 5 5-5 M3 16v5h18v-5"
      }
    ]
  },
  "upload": {
    "label": "Загрузить",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 16V3 M7 8l5-5 5 5 M3 16v5h18v-5"
      }
    ]
  },
  "print": {
    "label": "Печать",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M7 8V3h10v5 M7 17H3V8h18v9h-4 M7 14h10v7H7z M17 11h1"
      }
    ]
  },
  "original": {
    "label": "Оригинал",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M7 3h14v14h-4 M3 7h14v14H3z M6 17l4-5 4 5"
      },
      {
        "kind": "circle",
        "cx": 7,
        "cy": 11,
        "r": 1
      }
    ]
  },
  "attachment": {
    "label": "Вложение",
    "category": "media",
    "shapes": [
      {
        "kind": "path",
        "d": "M9 17 18 8a4 4 0 0 0-6-6L3 11a6 6 0 0 0 9 9l9-9 M7 14l8-8a1.5 1.5 0 0 1 2 2l-8 8a1.5 1.5 0 0 1-2-2"
      }
    ]
  },
  "sync": {
    "label": "Синхронизация",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 4v6h6 M3 10a9 9 0 0 1 16-4 M21 20v-6h-6 M21 14a9 9 0 0 1-16 4"
      }
    ]
  },
  "offline": {
    "label": "Нет связи",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3l18 18 M6 8a11 11 0 0 0-4 3 M10 6a12 12 0 0 1 12 5 M8 12l-2 2 M13 10a8 8 0 0 1 5 4 M9 17l3-2 3 2 M12 21v.1"
      }
    ]
  },
  "cloud": {
    "label": "Облако",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M7 19a5 5 0 1 1 0-10 6 6 0 0 1 12-1 5.5 5.5 0 0 1 0 11z"
      }
    ]
  },
  "local": {
    "label": "На устройстве",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3h18v14H3z M8 21h8 M12 17v4"
      }
    ]
  },
  "contribution": {
    "label": "Предложить изменение",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v13 M8 12l4 4 4-4 M3 14v7h18v-7 M3 17h4l2 2h6l2-2h4"
      }
    ]
  },
  "review": {
    "label": "Проверить изменения",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M4 3h11v7 M4 3v18h8 M7 7h5 M7 11h3 M19 18l3 3"
      },
      {
        "kind": "circle",
        "cx": 16,
        "cy": 14,
        "r": 5
      }
    ]
  },
  "accept": {
    "label": "Принять",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M4 12l5 5L20 5"
      }
    ]
  },
  "reject": {
    "label": "Отклонить",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 5l14 14 M19 5 5 19"
      }
    ]
  },
  "merge": {
    "label": "Объединить",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M6 20V4 M18 20v-4c0-6-12-3-12-10 M2 8l4-4 4 4"
      },
      {
        "kind": "circle",
        "cx": 6,
        "cy": 21,
        "r": 1
      },
      {
        "kind": "circle",
        "cx": 18,
        "cy": 21,
        "r": 1
      }
    ]
  },
  "compare": {
    "label": "Сравнить",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M12 3v18 M3 5h6v14H3z M15 5h6v14h-6z M5 9h2 M17 9h2 M5 13h2 M17 13h2"
      }
    ]
  },
  "backup": {
    "label": "Резервная копия",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 13v8h18v-8 M7 17h10 M12 15V3 M7 8l5-5 5 5"
      }
    ]
  },
  "restore": {
    "label": "Восстановить",
    "category": "sync",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 13v8h18v-8 M7 17h10 M12 3v10 M7 8l5 5 5-5"
      }
    ]
  },
  "atlas": {
    "label": "Атлас",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 7v5h14V7 M12 12v5 M2 3h6v4H2z M16 3h6v4h-6z M9 17h6v4H9z"
      }
    ]
  },
  "fan": {
    "label": "Веер",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M2 21a10 10 0 0 1 20 0z M6 21a6 6 0 0 1 12 0 M12 11v10 M5 14l7 7 7-7"
      }
    ]
  },
  "hourglass": {
    "label": "Песочные часы",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M4 3h16L4 21h16z M8 3v2 M16 3v2 M8 19v2 M16 19v2"
      }
    ]
  },
  "strata": {
    "label": "Стратиграфия",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 6h18 M3 12h18 M3 18h18 M6 3v12 M12 8v13 M18 3v13"
      }
    ]
  },
  "flows": {
    "label": "Потоки",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3c9 0 9 3 18 3 M3 8c9 0 9 3 18 3 M3 11c9 0 9 5 18 5 M3 15c9 0 9 5 18 5 M3 18c9 0 9 2 18 2 M3 21h18 M3 3v5 M3 11v4 M3 18v3 M21 6v5 M21 16v5"
      }
    ]
  },
  "kinship": {
    "label": "Родство",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 19 12 5l7 14 M6 8l12 1 M4 20h2 M18 20h2"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 4,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 4,
        "cy": 20,
        "r": 2
      },
      {
        "kind": "circle",
        "cx": 20,
        "cy": 20,
        "r": 2
      }
    ]
  },
  "genogram": {
    "label": "Генограмма",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 3h6v6H3z M9 6h6 M12 6v9 M6 18v-3h12v3 M3 18h6v4H3z"
      },
      {
        "kind": "circle",
        "cx": 18,
        "cy": 6,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 18,
        "cy": 20,
        "r": 2
      }
    ]
  },
  "geography": {
    "label": "География",
    "category": "modes",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2z M9 3v16 M15 5v16 M4 12c4-4 11 5 16-1"
      }
    ]
  },
  "settings": {
    "label": "Настройки",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 6h5 M14 6h7 M3 12h11 M20 12h1 M3 18h2 M11 18h10"
      },
      {
        "kind": "circle",
        "cx": 11,
        "cy": 6,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 17,
        "cy": 12,
        "r": 3
      },
      {
        "kind": "circle",
        "cx": 8,
        "cy": 18,
        "r": 3
      }
    ]
  },
  "help": {
    "label": "Помощь",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4 M12 18v.1"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 12,
        "r": 10
      }
    ]
  },
  "accessibility": {
    "label": "Доступность",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M3 8l9 2 9-2 M12 10v5 M7 22l5-7 5 7"
      },
      {
        "kind": "circle",
        "cx": 12,
        "cy": 4,
        "r": 2
      }
    ]
  },
  "theme": {
    "label": "Свет и лампа",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M15 3a9 9 0 1 0 6 14A10 10 0 0 1 15 3z"
      }
    ]
  },
  "language": {
    "label": "Язык",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M2 5h12 M8 2v3 M4 5c0 6 5 10 9 11 M12 5c0 6-5 10-9 11 M13 22l4-11 5 11 M15 18h5"
      }
    ]
  },
  "lock": {
    "label": "Закрытый доступ",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M5 10h14v11H5z M8 10V6a4 4 0 0 1 8 0v4 M12 14v3"
      }
    ]
  },
  "export": {
    "label": "Экспорт",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M11 3H3v18h18v-8 M10 14 21 3 M14 3h7v7"
      }
    ]
  },
  "import": {
    "label": "Импорт",
    "category": "system",
    "shapes": [
      {
        "kind": "path",
        "d": "M10 3H3v18h18v-8 M21 3 10 14 M10 7v7h7"
      }
    ]
  }
} as const;

/** Every icon name, as a type. */
export type IconName = keyof typeof icons;

/** The grid every glyph is drawn on. */
export const ICON_GRID = 24;
